"""Evaluate HumanEval predictions generated by test_code10.py."""

import argparse
import json
import os

from human_eval.data import write_jsonl
from human_eval.evaluation import evaluate_functional_correctness


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate HumanEval pass@k metrics.")
    parser.add_argument("--predict_file", type=str, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    print(args.predict_file)
    with open(args.predict_file, "r", encoding="utf-8") as handle:
        predicts = [json.loads(line) for line in handle if line.strip()]

    samples = []
    for row in predicts:
        responses = row["response"] if isinstance(row["response"], list) else [row["response"]]
        for response in responses:
            samples.append(
                {
                    "task_id": row["task_id"],
                    "completion": response.lstrip(": "),
                }
            )

    prediction_dir = os.path.dirname(args.predict_file)
    sample_file = os.path.join(prediction_dir, "sample.jsonl")
    write_jsonl(sample_file, samples)

    result = evaluate_functional_correctness(sample_file, k=[1, 5, 10])
    print(f"result:{result}")
    result["predict_file"] = args.predict_file

    output_dir = os.path.dirname(prediction_dir)
    with open(os.path.join(output_dir, "score.jsonl"), "a", encoding="utf-8") as handle:
        handle.write(json.dumps(result, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    main()
